### PR TITLE
JRuby 1.9 compatibility

### PR DESCRIPTION
**Pull request by kml**
Tests are not passing on JRuby

jruby --1.9 -S bundle exec rake

On JRuby 1.9 there is some problem with:
pid = spawn("ls"); p pid; Process.waitpid(pid)
Errno::ECHILD: No child processes - No child processes

jruby --1.9 -S irb
require 'subexec'
Subexec.run('ls')
...
LocalJumpError: break from proc-closure

Thanks to posix-spawn it's getting better!

### CODE REVIEW

**Comment by astjohn** [comment]
@kml, This was a huge help.  Thanks!

**Comment by kml** [comment]
It's still not perfect. Tests are passing, it works on irb, webrick, trinidad. But when deploying to TorqueBox it's not working.

**Comment by astjohn** [comment]
@kml, You're right.  I'm running into the same issue.  Have you found a solution yet?

**Comment by astjohn** [comment]
@kml, At @zenapsis, we just tried running Torquebox with `PRESERVE_JAVA_OPTS="true" torquebox run` and it seemed to work.

The issue was on Mac under 64bit JVM, JBoss was trying to force a 32bit environment because it was ignoring the global `JAVA_OPTS`.

**Comment by kml** [comment]
@astjohn I'm not using it on production yet, but not spawning is some solution for this problem ;)
https://github.com/kml/subexec/blob/exec/lib/subexec.rb#L54

**Pull request closed without merging**
