### PR TITLE
Use POSIX::Spawn if available to speed up forking

### PR DESCRIPTION
**Pull request by bdurand**
This pull request adds support to use the posix-spawn gem if it is available (https://github.com/rtomayko/posix-spawn). This can greatly speed up forking processes when the application has a large heap by preventing the entire heap from being copied to the new process. This is most noticeable on Linux and can be quite pronounced when the heap is from a large web application.
@gissues:{"order":20,"status":"backlog"}

### CODE REVIEW

**Comment by bdurand** [comment]
Any feedback on getting this merged? It really can significantly speed up large applications that fork many processes on POSIX systems.

**Comment by kaspergrubbe** [comment]
_Bump_

This would be nice to have.

**Comment by bdurand** [comment]
FYI this pull request is merged now with the latest (0.2.3) code from master.

**Comment by kaspergrubbe** [comment]
@bdurand Thank you so much :-)

**Comment by bdurand** [comment]
My previous commit to resolve conflicts with master accidentally disable POSIX::Spawn on Ruby version 1.9 and later. The latest commit fixes it (FYI @kaspergrubbe).

I do now have a graph showing what sort of improvement this change offers. This is the response time graph for a webapp that forks 5 processes per request using subexec. The big bump in the middle where response time doubled was just from using subexec without this patch in it.

image

**Comment by sergey-alekseev** [comment]
@bdurand @pkieltyka should this PR be merged?

**Comment by pkieltyka** [comment]
This gem is deprecated and I recommend the use of POSIX::Spawn instead.

**Comment by sergey-alekseev** [comment]
@pkieltyka what gem do you mean? `gem 'posix-spawn'`?

**Comment by kaspergrubbe** [comment]
From the readme:

screenie_1418734019_6907651

**Comment by sergey-alekseev** [comment]
@kaspergrubbe thanks, I should've been more patient. However it's been removed from very popular [mini_magick](https://github.com/minimagick/minimagick) only 3 months ago on [Sep 26](https://github.com/minimagick/minimagick/commit/f52b005189a1488c1ce3f6c6a2a0d540f1263199#diff-c5e19b867baeb294e7b61730ff066a06L22).

**Pull request closed without merging**
